brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
namesrvAddr=rmqnamesrv:9876
brokerIP1=127.0.0.1
listenPort=10911
autoCreateTopicEnable=true

# 性能优化
flushDiskType=ASYNC_FLUSH
sendMessageThreadPoolNums=8
sendThreadPoolQueueCapacity=50000
