security:
  internal-request:
    header-name: X-Internal-Auth
    secret: ${INTERNAL_REQUEST_SECRET:infinitechat_internal_auth_2026}

server:
  port: 8082

spring:
  application:
    name: AuthenticationService
  cloud:
    nacos:
      server-addr: 172.30.233.168:18375
      username: nacos
      password: nacos
      discovery:
        ip: 172.31.130.141
  #      server-addr: common-nacos-dev.magestack.cn:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.233.168:49152/InfiniteChat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: gK3T9n%q2M@j7Z4
    hikari:
      # ?????????
      maximum-pool-size: 30
      # ?????????
      minimum-idle: 10
      # ????????????????
      initialization-fail-timeout: 10000
      # ????????????
      idle-timeout: 30000
      # ???????????????
      max-lifetime: 60000
      # ????????????
      connection-timeout: 30000
      # ????????????
      validation-timeout: 3000
      # ???????SQL???????????SQL?
      connection-test-query: SELECT 1
      # ????????????
      pool-name: HikariCP
  jmx:
    enabled: true
  redis:
    database: 0
    host: 172.30.233.168
    port: 6399
    password: e65K4t8w2

minio:
  url: http://172.30.233.168:9000
  access-key: minioadmin
  secret-key: minioadmin

redisson:
  # ??Redisson????????????
  threads: 4  # ?????CPU?????????2?CPU???4

  # ??Netty IO????????????
  nettyThreads: 4  # ???????CPU??????

  # ?????????????????????
  codec: org.redisson.codec.JsonJacksonCodec  # ??JsonJacksonCodec??JSON??

  # ???????NIO???????????EPOLL?Linux?????
  # transportMode: "NIO"  # ????????? "EPOLL"

  singleServerConfig:
    # Redis???????????????redis:// ? rediss://?
    address: "redis://172.30.233.168:6399"

    # ??????????????????
    connectionPoolSize: 500  # ?????????Redis?????????

    # ????????????????????????
    connectionMinimumIdleSize: 100  # ?????connectionPoolSize?10%-20%

    # ????????????????????????
    idleConnectionTimeout: 10000  # ????????10000?10??

    # ??????????
    connectTimeout: 3000  # ????????3000?3??

    # Redis?????????
    timeout: 5000  # ?????????????????3000-5000

    # ????????????????
    retryAttempts: 3  # ????3?

    # ??????????????
    retryInterval: 1500  # ????????1500?1.5??

    password: "e65K4t8w2"
    database: 0

#  ??????????????health?metrics?
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
