server:
  port: 8084 # 🌟 注意：这里不要和上面的 8083 冲突
  tomcat:
    threads:
      max: 400
      min-spare: 50
    accept-count: 200

spring:
  application:
    name: MessagingService
  cloud:
    nacos:
      server-addr: 172.30.233.168:18375
      username: nacos
      password: nacos
      discovery:
        ip: 172.31.130.141
  redis:
    host: 172.30.233.168
    port: 6399
    password: e65K4t8w2
    lettuce:
      pool:
        max-active: 128
        max-idle: 64
        min-idle: 16
        max-wait: 500ms

  # 🌟 新增：MySQL 数据库配置 (用于 im_message 聊天记录落盘)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.233.168:49152/InfiniteChat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: gK3T9n%q2M@j7Z4
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      initialization-fail-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 5000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      pool-name: HikariCP
  jmx:
    enabled: true

minio:
  url: http://172.30.233.168:9000
  access-key: minioadmin
  secret-key: minioadmin

# 🌟 新增：RocketMQ 配置
rocketmq:
  name-server: 172.30.233.168:9876 # 替换为你真实的 RocketMQ NameServer 地址
  producer:
    group: im-message-producer-group # 默认 RocketMQTemplate：普通发送
    send-message-timeout: 1000
  # 抢红包事务专用生产者组（由 RedPacketTxRocketMQTemplate + @ExtRocketMQTemplateConfiguration 使用）
  # 官方无 rocketmq.transaction-producer-group 绑定项，勿与旧教程混用
  red-packet-tx-producer-group: im-red-packet-receive-tx-group

# 🌟 新增：Mybatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # XML 映射文件路径
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名自动映射
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl # 开启控制台打印 SQL，方便你今晚排查落库 Bug！

feign:
  circuitbreaker:
    enabled: true