#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { URL } = require('url');

const DEFAULTS = {
  url: 'ws://127.0.0.1:10010/api/v1/chat/message',
  tokens: '/opt/infinitechat/tokens.txt',
  connections: 100,
  rampUpMs: 10000,
  heartbeatMs: 30000,
  reportMs: 5000,
  connectTimeoutMs: 10000,
  reconnect: true,
  reconnectDelayMs: 1000,
  reconnectMaxDelayMs: 10000,
  maxReconnectAttempts: 0,
  ackPush: true,
  replyServerPing: true,
  verbose: false
};

function printHelp() {
  console.log([
    'Usage:',
    '  node scripts/ws_load_test.js [options]',
    '',
    'Options:',
    '  --url=<ws-url>                     WebSocket gateway URL',
    '  --tokens=<path>                   tokens.txt path generated by batch_login.sh',
    '  --connections=<n>                 Number of concurrent WS connections',
    '  --ramp-up-ms=<ms>                 Spread connection creation over this duration',
    '  --heartbeat-ms=<ms>               Client heartbeat interval',
    '  --report-ms=<ms>                  Metrics print interval',
    '  --connect-timeout-ms=<ms>         Handshake timeout per connection',
    '  --reconnect=<true|false>          Reconnect automatically after close',
    '  --reconnect-delay-ms=<ms>         Initial reconnect delay',
    '  --reconnect-max-delay-ms=<ms>     Max reconnect backoff',
    '  --max-reconnect-attempts=<n>      0 means unlimited reconnect attempts',
    '  --ack-push=<true|false>           Send ACK frame when a push contains messageId',
    '  --reply-server-ping=<true|false>  Reply heartbeat when server sends SERVER_PING',
    '  --verbose=<true|false>            Print per-connection open/close logs',
    '  --help                            Show this help',
    '',
    'Examples:',
    '  node scripts/ws_load_test.js --tokens=/opt/infinitechat/tokens.txt --connections=500 --ramp-up-ms=60000',
    '  node scripts/ws_load_test.js --connections=300 --reconnect=true --report-ms=2000',
    '',
    'Notes:',
    '  1. This script expects tokens.txt lines in the format userId|token.',
    '  2. Do not reuse the same user for multiple concurrent connections; the server supports single-login kickout.',
    '  3. Run wrk2 send_msg.lua in parallel if you want to observe real push throughput on the WS connections.'
  ].join('\n'));
}

function toCamelCase(key) {
  return key.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function parseBoolean(value, key) {
  if (value === 'true') {
    return true;
  }
  if (value === 'false') {
    return false;
  }
  throw new Error(`Invalid boolean for --${key}: ${value}`);
}

function parseNumber(value, key) {
  const num = Number(value);
  if (!Number.isFinite(num) || num < 0) {
    throw new Error(`Invalid number for --${key}: ${value}`);
  }
  return num;
}

function parseArgs(argv) {
  const options = { ...DEFAULTS };

  for (const arg of argv) {
    if (arg === '--help' || arg === '-h') {
      options.help = true;
      return options;
    }

    if (!arg.startsWith('--')) {
      throw new Error(`Unsupported argument: ${arg}`);
    }

    const body = arg.slice(2);
    const eqIndex = body.indexOf('=');
    const rawKey = eqIndex === -1 ? body : body.slice(0, eqIndex);
    const rawValue = eqIndex === -1 ? 'true' : body.slice(eqIndex + 1);
    const key = toCamelCase(rawKey);

    switch (key) {
      case 'url':
      case 'tokens':
        options[key] = rawValue;
        break;
      case 'connections':
      case 'rampUpMs':
      case 'heartbeatMs':
      case 'reportMs':
      case 'connectTimeoutMs':
      case 'reconnectDelayMs':
      case 'reconnectMaxDelayMs':
      case 'maxReconnectAttempts':
        options[key] = parseNumber(rawValue, rawKey);
        break;
      case 'reconnect':
      case 'ackPush':
      case 'replyServerPing':
      case 'verbose':
        options[key] = parseBoolean(rawValue, rawKey);
        break;
      default:
        throw new Error(`Unknown option: --${rawKey}`);
    }
  }

  return options;
}

function loadEntries(tokenFile) {
  const fullPath = path.resolve(tokenFile);
  const raw = fs.readFileSync(fullPath, 'utf8');
  const map = new Map();

  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed) {
      continue;
    }

    const parts = trimmed.split('|');
    if (parts.length < 2) {
      continue;
    }

    const userId = parts[0].trim();
    const token = parts[1].trim();
    if (!userId || !token || map.has(userId)) {
      continue;
    }

    map.set(userId, { userId, token });
  }

  return Array.from(map.values());
}

function buildWsUrl(baseUrl, token) {
  const url = new URL(baseUrl);
  url.searchParams.set('token', token);
  return url.toString();
}

function now() {
  return Date.now();
}

function formatDuration(ms) {
  const totalSeconds = Math.floor(ms / 1000);
  const seconds = totalSeconds % 60;
  const minutes = Math.floor(totalSeconds / 60) % 60;
  const hours = Math.floor(totalSeconds / 3600);
  return [hours, minutes, seconds].map((n) => String(n).padStart(2, '0')).join(':');
}

function incrementMapCounter(map, key) {
  const normalized = String(key);
  map.set(normalized, (map.get(normalized) || 0) + 1);
}

function mapToCompactString(map) {
  if (map.size === 0) {
    return '-';
  }

  return Array.from(map.entries())
    .sort((a, b) => Number(a[0]) - Number(b[0]))
    .map(([key, value]) => `${key}:${value}`)
    .join(',');
}

function createStats() {
  return {
    startedAt: now(),
    attemptedConnections: 0,
    openEvents: 0,
    closeEvents: 0,
    errorEvents: 0,
    unexpectedResponses: 0,
    activeConnections: 0,
    messagesReceived: 0,
    pushMessagesReceived: 0,
    serverPingMessages: 0,
    heartbeatsSent: 0,
    ackSent: 0,
    reconnectScheduled: 0,
    reconnectAttempts: 0,
    reconnectSuccess: 0,
    closeCodes: new Map(),
    responseCodes: new Map()
  };
}

function createClient(entry, index) {
  return {
    index,
    userId: entry.userId,
    token: entry.token,
    ws: null,
    isOpen: false,
    reconnectCount: 0,
    reconnectTimer: null,
    connectTimeoutTimer: null,
    heartbeatInterval: null,
    heartbeatStarter: null,
    lastError: null,
    lastCloseCode: null,
    lastCloseReason: null,
    lastMessageAt: null,
    authRejected: false
  };
}

function createHarness(options, entries, WebSocketImpl) {
  const stats = createStats();
  const clients = entries.map(createClient);
  let stopping = false;
  let reportTimer = null;

  function log(message) {
    console.log(`[${new Date().toISOString()}] ${message}`);
  }

  function verbose(message) {
    if (options.verbose) {
      log(message);
    }
  }

  function clearClientTimers(client) {
    if (client.connectTimeoutTimer) {
      clearTimeout(client.connectTimeoutTimer);
      client.connectTimeoutTimer = null;
    }
    if (client.reconnectTimer) {
      clearTimeout(client.reconnectTimer);
      client.reconnectTimer = null;
    }
    if (client.heartbeatStarter) {
      clearTimeout(client.heartbeatStarter);
      client.heartbeatStarter = null;
    }
    if (client.heartbeatInterval) {
      clearInterval(client.heartbeatInterval);
      client.heartbeatInterval = null;
    }
  }

  function sendJson(client, payload) {
    if (!client.ws || client.ws.readyState !== WebSocketImpl.OPEN) {
      return false;
    }

    client.ws.send(JSON.stringify(payload));
    return true;
  }

  function sendHeartbeat(client, reason) {
    const ok = sendJson(client, {
      type: 5,
      data: reason || 'CLIENT_PING'
    });

    if (ok) {
      stats.heartbeatsSent += 1;
    }
  }

  function sendAck(client, ackData) {
    if (!ackData || (!ackData.messageId && !(ackData.sessionId && ackData.seq != null))) {
      return;
    }

    const ok = sendJson(client, {
      type: 1,
      data: ackData
    });

    if (ok) {
      stats.ackSent += 1;
    }
  }

  function startHeartbeat(client) {
    if (options.heartbeatMs <= 0) {
      return;
    }

    const jitter = Math.min(1000, Math.floor(options.heartbeatMs / 5));
    const initialDelay = jitter > 0 ? Math.floor(Math.random() * jitter) : 0;

    client.heartbeatStarter = setTimeout(() => {
      sendHeartbeat(client, 'CLIENT_PING');
      client.heartbeatInterval = setInterval(() => {
        sendHeartbeat(client, 'CLIENT_PING');
      }, options.heartbeatMs);
    }, initialDelay);
  }

  function scheduleReconnect(client) {
    if (stopping || !options.reconnect || client.authRejected) {
      return;
    }

    if (options.maxReconnectAttempts > 0 && client.reconnectCount >= options.maxReconnectAttempts) {
      verbose(`client#${client.index} user=${client.userId} reached max reconnect attempts`);
      return;
    }

    const exponent = Math.min(client.reconnectCount, 5);
    const delay = Math.min(
      options.reconnectDelayMs * Math.pow(2, exponent),
      options.reconnectMaxDelayMs
    );

    client.reconnectCount += 1;
    stats.reconnectScheduled += 1;

    client.reconnectTimer = setTimeout(() => {
      connectClient(client, true);
    }, delay);
  }

  function handleMessage(client, raw) {
    stats.messagesReceived += 1;
    client.lastMessageAt = now();

    let parsed;
    try {
      parsed = JSON.parse(raw);
    } catch (error) {
      return;
    }

    if (parsed && parsed.type === 5) {
      stats.serverPingMessages += 1;
      if (options.replyServerPing) {
        sendHeartbeat(client, 'CLIENT_PONG');
      }
      return;
    }

    stats.pushMessagesReceived += 1;
    if (!options.ackPush || !parsed || typeof parsed !== 'object') {
      return;
    }

    const payload = (parsed && typeof parsed === 'object' && parsed.data && typeof parsed.data === 'object')
      ? parsed.data
      : parsed;

    if (payload && typeof payload === 'object') {
      const messageId = payload.messageId || payload.msgUuid || payload.id;
      const sessionId = payload.sessionId;
      const seq = payload.seq;
      if (messageId || (sessionId && seq != null)) {
        sendAck(client, { messageId, sessionId, seq });
      }
    }
  }

  function connectClient(client, isReconnect) {
    if (stopping) {
      return;
    }

    clearClientTimers(client);
    client.authRejected = false;
    client.lastError = null;

    const wsUrl = buildWsUrl(options.url, client.token);
    stats.attemptedConnections += 1;
    if (isReconnect) {
      stats.reconnectAttempts += 1;
    }

    const ws = new WebSocketImpl(wsUrl);
    client.ws = ws;

    client.connectTimeoutTimer = setTimeout(() => {
      if (ws.readyState !== WebSocketImpl.OPEN) {
        client.lastError = `connect timeout after ${options.connectTimeoutMs}ms`;
        try {
          ws.terminate();
        } catch (error) {
          client.lastError = `${client.lastError}; terminate failed: ${error.message}`;
        }
      }
    }, options.connectTimeoutMs);

    ws.on('open', () => {
      clearTimeout(client.connectTimeoutTimer);
      client.connectTimeoutTimer = null;

      if (!client.isOpen) {
        client.isOpen = true;
        stats.activeConnections += 1;
      }

      client.reconnectCount = 0;
      client.lastCloseCode = null;
      client.lastCloseReason = null;
      client.lastMessageAt = now();
      stats.openEvents += 1;
      if (isReconnect) {
        stats.reconnectSuccess += 1;
      }

      verbose(`open client#${client.index} user=${client.userId}`);
      startHeartbeat(client);
    });

    ws.on('message', (data) => {
      handleMessage(client, data.toString());
    });

    ws.on('unexpected-response', (_request, response) => {
      stats.unexpectedResponses += 1;
      incrementMapCounter(stats.responseCodes, response.statusCode);
      client.lastError = `unexpected response ${response.statusCode}`;
      if (response.statusCode === 401) {
        client.authRejected = true;
      }
      response.resume();
    });

    ws.on('error', (error) => {
      stats.errorEvents += 1;
      client.lastError = error.message;
    });

    ws.on('close', (code, reasonBuffer) => {
      clearClientTimers(client);
      if (client.isOpen) {
        client.isOpen = false;
        stats.activeConnections = Math.max(0, stats.activeConnections - 1);
      }

      client.lastCloseCode = code;
      client.lastCloseReason = reasonBuffer.toString();
      stats.closeEvents += 1;
      incrementMapCounter(stats.closeCodes, code);

      verbose(`close client#${client.index} user=${client.userId} code=${code} reason=${client.lastCloseReason || '-'}`);
      scheduleReconnect(client);
    });
  }

  function printReport(finalReport) {
    const elapsed = formatDuration(now() - stats.startedAt);
    const prefix = finalReport ? 'FINAL' : 'STAT ';
    log(
      `${prefix} elapsed=${elapsed}` +
      ` active=${stats.activeConnections}/${clients.length}` +
      ` attempted=${stats.attemptedConnections}` +
      ` opened=${stats.openEvents}` +
      ` closed=${stats.closeEvents}` +
      ` errors=${stats.errorEvents}` +
      ` unexpected=${stats.unexpectedResponses}` +
      ` recv=${stats.messagesReceived}` +
      ` push=${stats.pushMessagesReceived}` +
      ` serverPing=${stats.serverPingMessages}` +
      ` hbSent=${stats.heartbeatsSent}` +
      ` ackSent=${stats.ackSent}` +
      ` reconnectOk=${stats.reconnectSuccess}/${stats.reconnectAttempts}`
    );

    log(
      `${prefix} closeCodes=${mapToCompactString(stats.closeCodes)}` +
      ` responseCodes=${mapToCompactString(stats.responseCodes)}`
    );
  }

  function start() {
    reportTimer = setInterval(() => printReport(false), options.reportMs);

    const spacing = clients.length <= 1 ? 0 : Math.floor(options.rampUpMs / clients.length);
    clients.forEach((client, index) => {
      const delay = spacing * index;
      setTimeout(() => connectClient(client, false), delay);
    });
  }

  function stop() {
    if (stopping) {
      return;
    }
    stopping = true;

    if (reportTimer) {
      clearInterval(reportTimer);
      reportTimer = null;
    }

    for (const client of clients) {
      clearClientTimers(client);
      if (client.ws && (client.ws.readyState === WebSocketImpl.OPEN || client.ws.readyState === WebSocketImpl.CONNECTING)) {
        try {
          client.ws.close(1000, 'load test stopping');
        } catch (error) {
          client.lastError = error.message;
        }
      }
    }

    setTimeout(() => {
      printReport(true);
      process.exit(0);
    }, 1000);
  }

  return {
    start,
    stop,
    printReport,
    stats,
    clients
  };
}

function main() {
  let options;
  try {
    options = parseArgs(process.argv.slice(2));
  } catch (error) {
    console.error(error.message);
    printHelp();
    process.exit(1);
  }

  if (options.help) {
    printHelp();
    return;
  }

  let WebSocketImpl;
  try {
    WebSocketImpl = require('ws');
  } catch (error) {
    console.error('Missing dependency "ws".');
    console.error('Install it with: npm install ws');
    process.exit(1);
  }

  const entries = loadEntries(options.tokens);
  if (entries.length === 0) {
    console.error(`No valid tokens found in ${options.tokens}`);
    process.exit(1);
  }

  if (options.connections > entries.length) {
    console.warn(
      `Requested ${options.connections} connections but only ${entries.length} unique users exist in tokens.txt. ` +
      `Capping to ${entries.length} to avoid same-user kickout.`
    );
    options.connections = entries.length;
  }

  const selectedEntries = entries.slice(0, options.connections);

  console.log([
    `Starting WS load harness`,
    `  url=${options.url}`,
    `  tokens=${path.resolve(options.tokens)}`,
    `  connections=${selectedEntries.length}`,
    `  rampUpMs=${options.rampUpMs}`,
    `  heartbeatMs=${options.heartbeatMs}`,
    `  reportMs=${options.reportMs}`,
    `  reconnect=${options.reconnect}`,
    `  ackPush=${options.ackPush}`,
    `  replyServerPing=${options.replyServerPing}`
  ].join('\n'));

  const harness = createHarness(options, selectedEntries, WebSocketImpl);
  process.on('SIGINT', () => harness.stop());
  process.on('SIGTERM', () => harness.stop());
  harness.start();
}

main();
