spring:
  application:
    name: RealTimeCommunicationService
  cloud:
    nacos:
      server-addr: 172.30.233.168:18375
      username: nacos
      password: nacos
      discovery:
        ip: 172.31.130.141
        metadata:
          ws-protocol: ${netty.ws-protocol}
          ws-port: ${netty.port}
          ws-path: ${netty.ws-path}
  redis:
    host: 172.30.233.168
    port: 6399
    password: e65K4t8w2

server:
  port: 8083 # 供内部微服务调用的 HTTP Push 接口端口

netty:
  port: 9101 # 供前端 WebSocket 连入的长连接物理端口
  ws-protocol: ws
  ws-path: /api/v1/chat/message

rocketmq:
  name-server: 172.30.233.168:9876
  producer:
    group: rtc-push-producer-group
  consumer:
    max-reconsume-times: 3

im:
  node:
    id: NODE_1
